### ISSUE TITLE
pretty quits without any error when exception raised

### ISSUE THREAD

**Issue by hamidb80** [treeform/pretty#2]
## Code
```nim
import pretty

proc helloAndre(): int =
  raise newException(ValueError, "what")

when defined bug:
  print helloAndre()
else:
  let r = helloAndre()
  print r
```

## Expected Output
```
Error: unhandled exception: what [ValueError]
```

## Current Output
```
```

**Comment by hamidb80** [comment]
I think it does not capture any exceptions in general

**Comment by Patitotective** [comment]
Hey, I created a PR to fix this but the owner of this repository doesn't seem very active so feel free to use my fork that contains various fixes: https://github.com/Patitotective/pretty.
